---
- name: Actualizar paquetes en RHEL 9
  hosts: all
  become: yes

  vars:
    # Modo de parchado:
    #   security        -> solo parches de seguridad (RHSA)
    #   bugfix          -> solo correcciones de errores (RHBA)
    #   security_bugfix -> seguridad + bugfix
    #   full            -> todas las actualizaciones
    #   simulate        -> solo simulación (no aplica cambios)
    patch_mode: "security"

  tasks:
    - name: Ejecutar actualización del sistema según modo
      ansible.builtin.shell: |
        {% if patch_mode == "simulate" %}
        dnf update -y --setopt=tsflags=test --refresh
        {% elif patch_mode == "security" %}
        dnf update -y --security --refresh
        {% elif patch_mode == "bugfix" %}
        dnf update -y --bugfix --refresh
        {% elif patch_mode == "security_bugfix" %}
        dnf update -y --security --bugfix --refresh
        {% elif patch_mode == "full" %}
        dnf update -y --refresh
        {% else %}
        echo "⚠️  patch_mode inválido: {{ patch_mode }}" && exit 1
        {% endif %}
      environment:
        LANG: en_US.UTF-8
        LC_ALL: en_US.UTF-8
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
