---
- name: Parchar Windows con Windows Update (robusto)
  hosts: all
  gather_facts: no

  vars:
    categories:
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups

  tasks:
    - name: Aplicar actualizaciones hasta agotar pendientes
      ansible.windows.win_updates:
        category_names: "{{ categories }}"
        state: installed
        reboot: no                   # el módulo reinicia si hace falta
        reboot_timeout: 3600          # tiempo suficiente para volver
        log_path: "C:\\Windows\\Temp\\ansible-winupdates.log"
      register: wu
      # repetir “pasadas” hasta que no haya nada por instalar
      until: wu.installed_update_count | default(0) == 0
      retries: 4
      delay: 60

    # Espera defensiva a que WinRM quede estable tras el último reboot
    - name: Esperar WinRM arriba
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 600

    - name: Comprobación final
      ansible.windows.win_ping:
