---
- name: Parchar Windows con Windows Update
  hosts: windows
  gather_facts: no

  tasks:
    - name: Instalar Actualizaciones Críticas y de Seguridad 
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        state: installed
        reboot: yes
