---
- name: Parchar Windows con manejo de SSU y exclusiones
  hosts: all
  gather_facts: no

  vars:
    log_path: "C:\\Windows\\Temp\\ansible-winupdates.log"
    # Si descubrimos un KB problemático, agrégalo aquí o como extra var en AWX
    reject_kbs: []   # ejemplo: ["KB5036893","KB5034763"]

  tasks:
    - name: Buscar actualizaciones disponibles (solo inventario)
      ansible.windows.win_updates:
        state: searched
      register: search_all
    
    - name: Normalizar estructuras devueltas por win_updates
      ansible.builtin.set_fact:
        updates_norm: >-
          {{
            (search_all.updates is mapping)
            | ternary(
                search_all.updates | dict2items | map(attribute='value') | list,
                (search_all.updates | default([]) | list)
              )
          }}
        filtered_norm: >-
          {{
            search_all.filtered_updates | default({}) | dict2items | map(attribute='value') | list
          }}

    - name: Mostrar lista encontrada (KBs/títulos) segura
      ansible.builtin.debug:
        msg:
          kbs: "{{ (updates_norm + filtered_norm) | map(attribute='kb') | map('first') | list | default([]) }}"
          titles: "{{ (updates_norm + filtered_norm) | map(attribute='title') | list | default([]) }}"
      when: (updates_norm | length + filtered_norm | length) > 0
    

    # 1) SSU primero
    - name: Instalar únicamente Servicing Stack Updates
      ansible.windows.win_updates:
        category_names: ['ServicingStackUpdates']
        state: installed
        reboot: yes
        reboot_timeout: 3600
        log_path: "{{ log_path }}"
      register: ssu_result

    - name: Esperar WinRM estable tras SSU
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 1200

    # 2) Resto de categorías en una o más pasadas
    - name: Instalar críticas/seguridad/rollups (en olas)
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        state: installed
        reboot: yes
        reboot_timeout: 3600
        log_path: "{{ log_path }}"
        reject_list: "{{ reject_kbs }}"
      register: wu
      until: wu.failed_update_count|default(0) == 0
      retries: 2
      delay: 60

    - name: Esperar WinRM estable tras la última pasada
      ansible.builtin.wait_for_connection:
        delay: 15
        timeout: 600

    # 3) Si todavía hay fallos, reporta claramente cuáles
    - name: Reportar KBs fallidos (si los hay)
      ansible.builtin.fail:
        msg: >-
          Fallaron KBs: {{ wu.updates | selectattr('result','equalto','Failed') |
                           map(attribute='kb') | list }}.
          Agrégalos a 'reject_kbs' para excluirlos temporalmente y vuelve a ejecutar.
          Revisa el log en {{ log_path }}.
      when: wu.failed_update_count|default(0) > 0
